// flow-typed signature: 28002a1d1b7b09ce86dfcd413808979a
// flow-typed version: <<STUB>>/izitoast_v^1.1.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'izitoast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'izitoast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'izitoast/dist/js/iziToast' {
  declare module.exports: any;
}

declare module 'izitoast/dist/js/iziToast.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'izitoast/dist/js/iziToast.js' {
  declare module.exports: $Exports<'izitoast/dist/js/iziToast'>;
}
declare module 'izitoast/dist/js/iziToast.min.js' {
  declare module.exports: $Exports<'izitoast/dist/js/iziToast.min'>;
}
